database:
  db : "root:csquan253905@tcp(127.0.0.1:3306)/Hui_TxState?charset=utf8mb4"
  block_worker: 5
  tx_worker: 1
  sql_batch: 500
  retry_times: 5
  retry_interval: 300

server_conf:
  users:
    admin: "10244201"

chains:
  Hui:
    id: 8888
    rpc_url: "http://43.198.66.226:8545"
    fetch_timeout: 3000

log:
  stdout:
    enable: true
    level: 5
  file:
    enable: true
    path: "/tmp/hermes-rebalance/app.log"
    level: 4
  kafka:
    enable: false
    topic: "huobi-test"
    kafka_servers:
      - "kafka-1.huobidev.com:9092"
      - "kafka-2.huobidev.com:9092"
      - "kafka-3.huobidev.com:9092"
    level: 3
